export const EVENT_ACTIONS = {
    GET_EVENTS: 'GET_EVENTS',
    REQUEST_START: 'REQUEST_START',
    REQUEST_END: 'REQUEST_END',
    SET_EVENTS: 'SET_EVENTS',
    GET_EVENT_INFO: 'GET_EVENT_INFO',
    SET_EVENT_INFO: 'SET_EVENT_INFO'
}

export const triggerGet = () => ({
    type: EVENT_ACTIONS.GET_EVENTS,
});