export const EVENT_ACTIONS = {
    FETCH_EVENTS: 'FETCH_EVENTS',
    REQUEST_START: 'REQUEST_START',
    REQUEST_END: 'REQUEST_END',
    SET_EVENTS: 'SET_EVENTS',
    FETCH_EVENT_INFO: 'FETCH_EVENT_INFO',
    SET_EVENT_INFO: 'SET_EVENT_INFO',
    CREATE_EVENT: 'CREATE_EVENT',
    UPDATE_EVENT: 'UPDATE_EVENT',
    DELETE_EVENT: 'DELETE_EVENT',
}

export const triggerGet = () => ({
    type: EVENT_ACTIONS.FETCH_EVENTS,
});